name: Question

description: Ask a general question.

title: "[Question]: "

labels: ["question", "triage"]

assignees: ["zjoasan", "bud3699", "itsmikethetech"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! Please provide as much detail as possible to help us understand your question.
  
  - type: textarea
    id: question-info
    attributes:
      label: What is your question?
      description: Provide details about your question.
      placeholder: |
        Describe your question clearly so we can assist you effectively.
    validations:
      required: true
  
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Any extra details that might help us answer your question.
      placeholder: |
        Provide any relevant context, screenshots, or references.
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you if we need more information?
      placeholder: ex. email@example.com
    validations:
      required: false
